# Flake entry point: pin inputs and expose the system, home, and dev tools.

{
  description = "NixOS and Home Manager workstation configuration";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-26.05";
    # Steam popup menus need the xwayland-satellite 0.8.3 fix.
    nixpkgs-xwayland-satellite.url = "github:NixOS/nixpkgs/nixos-unstable";
    home-manager = {
      url = "github:nix-community/home-manager/release-26.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    stylix = {
      url = "github:nix-community/stylix/release-26.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    sops-nix = {
      url = "github:Mic92/sops-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nixcord = {
      url = "github:4evy/nixcord";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.nixpkgs-nixcord.follows = "nixpkgs";
      inputs.home-manager.follows = "home-manager";
    };
    # Agent CLIs and desktop apps update faster than the stable Nixpkgs branch.
    # Keep this input's tested unstable Nixpkgs pin instead of using `follows`.
    llm-agents.url = "github:numtide/llm-agents.nix";
  };

  outputs =
    {
      nixpkgs,
      nixpkgs-xwayland-satellite,
      home-manager,
      stylix,
      sops-nix,
      nixcord,
      llm-agents,
      ...
    }:
    let
      # Change these values when adapting the flake to another workstation.
      setup = rec {
        system = "x86_64-linux";
        hostName = "PC";
        username = "yz";
        homeDirectory = "/home/${username}";
        # Preserve these values for an existing installation.
        stateVersion = {
          system = "26.05";
          home = "26.05";
        };
        # Etc/GMT signs are reversed: GMT-3 is a fixed UTC+03:00.
        timeZone = "Etc/GMT-3";
        locale = "en_US.UTF-8";
        keyboard = {
          layouts = [
            "us"
            "ara"
          ];
          toggle = "grp:caps_toggle";
        };
        monitor = {
          match = "LG Electronics LG ULTRAWIDE 0x00021DA6";
          mode = "2560x1080@74.991";
        };
        graphics = {
          videoDrivers = [ "nvidia" ];
          # Test the proprietary kernel module without GSP after GPU hangs.
          nvidiaOpen = false;
          nvidiaGsp = false;
        };
        androidLab = {
          acceptLicense = true;
          apiLevel = "35";
          imageType = "google_apis";
          abi = "x86_64";
          avdName = "pi-re-api35";
          port = 5580;
          cores = 4;
          memoryMiB = 4096;
          bootTimeoutSeconds = 180;
          gpuMode = "swangle";
          hardwareVideoDecoder = false;
          display = {
            width = 720;
            height = 1600;
            density = 320;
          };
          proxyPort = 8089;
        };
        gitIdentity = {
          name = username;
          email = "git.remarry972@simplelogin.com";
          githubEmail = "260740417+yzua@users.noreply.github.com";
          signingKey = "${homeDirectory}/.ssh/id_ed25519.pub";
        };
      };
      inherit (setup) system;
      pkgs = import nixpkgs {
        inherit system;
        # Home Manager uses this package set; approve only the requested apps.
        config = {
          android_sdk.accept_license = setup.androidLab.acceptLicense;
          allowUnfreePredicate =
            pkg:
            let
              name = nixpkgs.lib.getName pkg;
            in
            builtins.elem name [
              "google-chrome"
              "vscode"
              "androidsdk"
              "platform-tools"
              "build-tools"
              "emulator"
              "platforms"
              "cmdline-tools"
              "system-image-${setup.androidLab.apiLevel}-${setup.androidLab.imageType}-${setup.androidLab.abi}"
            ]
            || nixpkgs.lib.hasPrefix "android-sdk-" name;
        };
      };
      androidTools = import ./packages/android-re-toolchain {
        inherit pkgs;
        inherit (setup) androidLab;
      };
      # The Rust rewrite is newer than Nixpkgs's legacy Qt LibrePods package.
      librepodsPackage = pkgs.callPackage ./packages/librepods-rust { };
      # Reuse one formatter for `nix fmt` and the development shell.
      formatter = pkgs.nixfmt-tree.override {
        runtimeInputs = [ pkgs.shfmt ];
        settings.formatter.shfmt = {
          command = "shfmt";
          options = [
            "-i"
            "2"
            "-w"
          ];
          includes = [ "*.sh" ];
        };
        # This file is generated by nixos-generate-config; leave it unchanged.
        settings.formatter.nixfmt.excludes = [
          "hardware-configuration.nix"
          "**/hardware-configuration.nix"
        ];
      };
      home = home-manager.lib.homeManagerConfiguration {
        inherit pkgs;
        extraSpecialArgs = {
          inherit setup androidTools;
          aiPackages = llm-agents.packages.${system};
          inherit nixcord;
        };
        modules = [
          ./home-manager/home.nix
          stylix.homeModules.stylix
          sops-nix.homeManagerModules.sops
        ];
      };
    in
    {
      nixosConfigurations.${setup.hostName} = nixpkgs.lib.nixosSystem {
        inherit system;
        specialArgs = {
          inherit setup librepodsPackage;
          xwaylandSatellite = nixpkgs-xwayland-satellite.legacyPackages.${system}.xwayland-satellite;
        };
        modules = [ ./hosts/PC/default.nix ];
      };

      homeConfigurations."${setup.username}@${setup.hostName}" = home;
      checks.${system}."home-${setup.username}-${setup.hostName}" = home.activationPackage;

      formatter.${system} = formatter;

      packages.${system} = {
        librepods-rust = librepodsPackage;
        pi-re = nixpkgs.lib.findFirst (
          package: nixpkgs.lib.getName package == "pi-re"
        ) (throw "The selected Home Manager profile does not provide pi-re") home.config.home.packages;
        android-re-sdk = androidTools.sdk;
        android-re-agent-device = androidTools.agentDevice;
        android-re-guest-signal = androidTools.guestSignal;
        android-re-toolchain = androidTools.environment;
      };
      devShells.${system} = {
        android-re = pkgs.mkShell {
          inherit (androidTools) packages;
          ANDROID_HOME = androidTools.sdkRoot;
          ANDROID_SDK_ROOT = androidTools.sdkRoot;
          AGENT_DEVICE_NO_UPDATE_NOTIFIER = "1";
        };

        # Project-only tooling; no change to the system or home packages.
        default = pkgs.mkShell {
          packages = [
            pkgs.git
            pkgs.just
            pkgs.age
            pkgs.sops
            home-manager.packages.${system}.default
            formatter
            pkgs.nixfmt
            pkgs.shfmt
            pkgs.statix
            pkgs.deadnix
            pkgs.shellcheck
            pkgs.biome
            pkgs.ruff
            pkgs.rumdl
            pkgs.python3
          ];
        };
      };
    };
}
