# Flake entry point: pin inputs and expose the system, home, and dev tools.

{
  description = "NixOS configuration for PC";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-26.05";
    home-manager = {
      url = "github:nix-community/home-manager/release-26.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    stylix = {
      url = "github:nix-community/stylix/release-26.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    sops-nix = {
      url = "github:Mic92/sops-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nixcord = {
      url = "github:4evy/nixcord";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.nixpkgs-nixcord.follows = "nixpkgs";
      inputs.home-manager.follows = "home-manager";
    };
    # Agent CLIs and desktop apps update faster than the stable Nixpkgs branch.
    # Keep this input's tested unstable Nixpkgs pin instead of using `follows`.
    llm-agents.url = "github:numtide/llm-agents.nix";
    # Skill content only; pin it separately from the agent executables.
    mattPocockSkills = {
      url = "github:mattpocock/skills";
      flake = false;
    };
  };

  outputs =
    {
      nixpkgs,
      home-manager,
      stylix,
      sops-nix,
      nixcord,
      llm-agents,
      mattPocockSkills,
      ...
    }:
    let
      system = "x86_64-linux";
      # Share this account's identity between the host and standalone home profile.
      username = "yz";
      homeProfile = {
        inherit username;
        homeDirectory = "/home/${username}";
        gitIdentity = {
          name = username;
          email = "git.remarry972@simplelogin.com";
          githubEmail = "260740417+yzua@users.noreply.github.com";
        };
      };
      pkgs = import nixpkgs {
        inherit system;
        # Home Manager uses this package set; approve only the requested apps.
        config.allowUnfreePredicate =
          pkg:
          builtins.elem (nixpkgs.lib.getName pkg) [
            "google-chrome"
            "vscode"
          ];
      };
      # Reuse one formatter for `nix fmt` and the development shell.
      formatter = pkgs.nixfmt-tree.override {
        runtimeInputs = [ pkgs.shfmt ];
        settings.formatter.shfmt = {
          command = "shfmt";
          options = [
            "-i"
            "2"
            "-w"
          ];
          includes = [ "*.sh" ];
        };
        # This file is generated by nixos-generate-config; leave it unchanged.
        settings.formatter.nixfmt.excludes = [
          "hardware-configuration.nix"
          "**/hardware-configuration.nix"
        ];
      };
      home = home-manager.lib.homeManagerConfiguration {
        inherit pkgs;
        extraSpecialArgs = {
          inherit homeProfile;
          aiPackages = llm-agents.packages.${system};
          inherit mattPocockSkills nixcord;
        };
        modules = [
          ./home-manager/home.nix
          stylix.homeModules.stylix
          sops-nix.homeManagerModules.sops
        ];
      };
    in
    {
      nixosConfigurations.PC = nixpkgs.lib.nixosSystem {
        inherit system;
        specialArgs = { inherit username; };
        modules = [ ./hosts/PC/default.nix ];
      };

      homeConfigurations."${username}@PC" = home;
      checks.${system}."home-${username}-PC" = home.activationPackage;

      formatter.${system} = formatter;

      # Project-only tooling; no change to the system or home packages.
      devShells.${system}.default = pkgs.mkShell {
        packages = [
          pkgs.git
          pkgs.just
          pkgs.age
          pkgs.sops
          home-manager.packages.${system}.default
          formatter
          pkgs.nixfmt
          pkgs.shfmt
          pkgs.statix
          pkgs.deadnix
          pkgs.shellcheck
        ];
      };
    };
}
